name: '[Release] On Publish'

on:
  # push:
  #   branches:
  #     - "**" # matches every branch
  # pull_request:
  #   branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: upload artifacts
        # if: ${{ github.event_name == 'release' && github.event.action == 'publish' }}env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        working-directory: ./out
        run: |
          gh release upload "manual-release" hello
          # echo ${{ github.token }} | gh auth login --with-token
          # for filename in ./* ; do
          #   [ -e "$filename" ] || continue
          #   echo "Processing $filename ..."
          #   gh release upload --repo ${{ github.repository }} test $filename
          #   # gh release upload ${{ github.event.release.tag_name}} $filename
          # done
